name: CaptureBase
version: '${project.version}'
main: lapitanplugins.capturebase.CaptureBase
api-version: 1.16
authors: [ lapitan ]
commands:
  test: {}
  test2: {}
  mineMob: {}
  classTP: {}
  flag: {}
  addTeleport: {}
  setBoss: {}
  setAfterPreparing: {}
  class: {}
  team: {}
  setSpawn: {}
  start: {}
